steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--secret', 'id=deploy_key,src=/workspace/deploy_key',
      '-t', 'gcr.io/hpc-data-finder-poc-7930/github.com/nyuhpc/cd-finder:latest',
      '-f', 'docker/Dockerfile',
      '.'
    ]
    secretEnv: ['DEPLOY_KEY']

availableSecrets:
  secretManager:
    - versionName: projects/721023221862/secrets/deploy_key/versions/1
      env: 
        - DEPLOY_KEY

images:
  - 'gcr.io/hpc-data-finder-poc-7930/github.com/nyuhpc/cd-finder:latest'

options:
  logging: NONE
