steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/hpc-data-finder-poc-7930/github.com/nyuhpc/cd-finder:latest',
    '-f', 'docker/Dockerfile',
    '.'
  ]
  
images:
- 'gcr.io/hpc-data-finder-poc-7930/github.com/nyuhpc/cd-finder:latest'

options:
  logging: NONE

